server {
    listen 80;
    server_name akins-stage0.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name akins-stage0.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/akins-stage0.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/akins-stage0.duckdns.org/privkey.pem;

    location / {
        root /var/www/html;
        index index.html;
    }

    location /api {
        add_header Content-Type application/json;
        return 200 '{"message": "HNG14 Stage 1", "track": "DevOps", "username": "akin_hng"}';
    }
}
